# -*- coding: utf-8 -*-
"""submission m.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyJXdLeqP7na0GTsF5DHTZ6AAJaRoFsl
"""

!pip install PyPDF2 psycopg2-binary sentence-transformers pinecone-client google-generativeai openai tqdm

import os

pdf_files = [f for f in os.listdir() if f.endswith('.pdf.pdf')]
print("Found PDF files:", pdf_files)

import os
import PyPDF2
from tqdm import tqdm
import re

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def load_and_chunk_pdf(pdf_path, max_chunk_size=500):
    chunks = []
    try:
        with open(pdf_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            for page_num, page in enumerate(reader.pages):
                try:
                    text = page.extract_text()
                    if not text or len(text.strip()) < 10:
                        continue

                    text = clean_text(text)

                    if len(text) <= max_chunk_size:
                        chunks.append({
                            'text': text,
                            'metadata': {
                                'file_name': os.path.basename(pdf_path),
                                'page': page_num + 1,
                                'chunk_id': f"{os.path.basename(pdf_path)}_page_{page_num + 1}"
                            }
                        })
                    else:
                        words = text.split()
                        current_chunk = []
                        current_length = 0

                        for word in words:
                            if current_length + len(word) > max_chunk_size and current_chunk:
                                chunk_text = ' '.join(current_chunk)
                                chunks.append({
                                    'text': chunk_text,
                                    'metadata': {
                                        'file_name': os.path.basename(pdf_path),
                                        'page': page_num + 1,
                                        'chunk_id': f"{os.path.basename(pdf_path)}_page_{page_num + 1}_chunk_{len(chunks)}"
                                    }
                                })
                                current_chunk = [word]
                                current_length = len(word)
                            else:
                                current_chunk.append(word)
                                current_length += len(word) + 1

                        if current_chunk:
                            chunk_text = ' '.join(current_chunk)
                            chunks.append({
                                'text': chunk_text,
                                'metadata': {
                                    'file_name': os.path.basename(pdf_path),
                                    'page': page_num + 1,
                                    'chunk_id': f"{os.path.basename(pdf_path)}_page_{page_num + 1}_chunk_{len(chunks)}"
                                }
                            })
                except Exception as e:
                    print(f"Error processing page {page_num + 1} of {pdf_path}: {e}")
    except Exception as e:
        print(f"Error reading PDF {pdf_path}: {e}")
        return []

    return chunks

# Scan PDFs in current directory
all_chunks = []
pdf_files = [f for f in os.listdir() if f.endswith('.pdf')]

if not pdf_files:
    print("No PDF files found. Please upload them using the Jupyter interface.")
else:
    print(f"Found {len(pdf_files)} PDF files")
    for file in tqdm(pdf_files, desc="Processing PDFs"):
        chunks = load_and_chunk_pdf(file)
        all_chunks.extend(chunks)
        print(f"Processed {file}: {len(chunks)} chunks")

print(f"Total chunks created: {len(all_chunks)}")

# Sample output
if all_chunks:
    print("\nSample chunks:")
    for i, chunk in enumerate(all_chunks[:3]):
        print(f"Chunk {i+1}:")
        print(f"Text preview: {chunk['text'][:100]}...")
        print(f"Metadata: {chunk['metadata']}")
        print("-" * 50)

!pip install psycopg2-binary

import psycopg2
import json
from psycopg2.extras import RealDictCursor

def create_database_table():
    """Create the chunks table if it doesn't exist"""
    try:
        conn = psycopg2.connect(
            dbname="postgres",  # Connect to default postgres db first
            user="postgres",
            password="Madhav25$",  # Replace with your password
            host="localhost",
            port=5432
        )
        conn.autocommit = True
        cur = conn.cursor()

        # Create database if it doesn't exist
        cur.execute("SELECT 1 FROM pg_database WHERE datname = 'project_db'")
        if not cur.fetchone():
            cur.execute("CREATE DATABASE project_db")
            print("Database 'project_db' created")

        cur.close()
        conn.close()

        # Connect to project_db and create table
        conn = psycopg2.connect(
            dbname="project_db",
            user="postgres",
            password="Madhav25$",  # Replace with your password
            host="localhost",
            port=5432
        )
        cur = conn.cursor()

        # Create table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS chunks (
                id SERIAL PRIMARY KEY,
                text TEXT NOT NULL,
                metadata JSONB NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Create index for better search performance
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_chunks_metadata
            ON chunks USING GIN (metadata)
        """)

        conn.commit()
        cur.close()
        conn.close()
        print("Table 'chunks' created successfully")

    except Exception as e:
        print(f"Database setup error: {e}")
        return False
    return True

def insert_chunks_postgres(chunks):
    """Insert chunks into PostgreSQL database"""
    if not chunks:
        print("No chunks to insert")
        return

    try:
        conn = psycopg2.connect(
            dbname="project_db",
            user="postgres",
            password="Madhav25$",  # Replace with your password
            host="localhost",
            port=5432
        )
        cur = conn.cursor()

        # Clear existing data (optional)
        cur.execute("DELETE FROM chunks")

        # Insert new chunks
        for chunk in tqdm(chunks, desc="Inserting into PostgreSQL"):
            cur.execute(
                "INSERT INTO chunks (text, metadata) VALUES (%s, %s)",
                (chunk['text'], json.dumps(chunk['metadata']))
            )

        conn.commit()
        print(f"Successfully inserted {len(chunks)} chunks into PostgreSQL")

        # Verify insertion
        cur.execute("SELECT COUNT(*) FROM chunks")
        count = cur.fetchone()[0]
        print(f"Total chunks in database: {count}")

        cur.close()
        conn.close()

    except Exception as e:
        print(f"Error inserting chunks into PostgreSQL: {e}")

# Run database setup and insertion
if create_database_table() and all_chunks:
    insert_chunks_postgres(all_chunks)

!pip install pinecone-client==3.0.0
!pip install sentence-transformers

# Install pinecone-client v3 if needed
# !pip install pinecone-client

from pinecone import Pinecone, ServerlessSpec
from sentence_transformers import SentenceTransformer
import time

# Initialize Pinecone (replace with your API key)
PINECONE_API_KEY = "pcsk_6pgogE_LsaaGxEkbbzwqBUPhJGqeEed4PWfzCHFRrnhzZ4AAKCAu78kvDgP8UehZoyeo2d"  # Replace with your actual API key

def setup_pinecone_index():
    """Setup Pinecone index"""
    try:
        pc = Pinecone(api_key=PINECONE_API_KEY)

        index_name = "doc-index"

        # Check if index exists
        existing_indexes = pc.list_indexes()
        if index_name not in [idx.name for idx in existing_indexes]:
            # Create index
            pc.create_index(
                name=index_name,
                dimension=384,  # Dimension for all-MiniLM-L6-v2 model
                metric="cosine",
                spec=ServerlessSpec(
                    cloud="aws",
                    region="us-east-1"  # Choose your preferred region
                )
            )
            print(f"Created index: {index_name}")
            time.sleep(60)  # Wait for index to be ready

        index = pc.Index(index_name)
        print(f"Connected to index: {index_name}")
        return index

    except Exception as e:
        print(f"Pinecone setup error: {e}")
        return None

# Initialize embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding model loaded")

def embed_and_store_pinecone(chunks, index):
    """Embed chunks and store in Pinecone"""
    if not chunks or not index:
        print("No chunks or index available")
        return

    batch_size = 100

    for i in tqdm(range(0, len(chunks), batch_size), desc="Embedding and storing"):
        batch = chunks[i:i + batch_size]
        vectors_to_upsert = []

        for j, chunk in enumerate(batch):
            try:
                # Generate embedding
                vector = embedding_model.encode(chunk['text']).tolist()

                # Prepare metadata (Pinecone has metadata size limits)
                metadata = {
                    'text': chunk['text'][:1000],  # Limit text size in metadata
                    'file_name': chunk['metadata']['file_name'],
                    'page': chunk['metadata']['page'],
                    'chunk_id': chunk['metadata']['chunk_id']
                }

                vectors_to_upsert.append({
                    'id': f"chunk-{i+j}",
                    'values': vector,
                    'metadata': metadata
                })

            except Exception as e:
                print(f"Error processing chunk {i+j}: {e}")
                continue

        # Upsert batch
        if vectors_to_upsert:
            try:
                index.upsert(vectors_to_upsert)
            except Exception as e:
                print(f"Error upserting batch {i//batch_size}: {e}")

    # Check index stats
    stats = index.describe_index_stats()
    print(f"Index stats: {stats}")

# Setup and run embedding
if PINECONE_API_KEY:  # Make sure API key is set
    pinecone_index = setup_pinecone_index()
    if pinecone_index and all_chunks:
        embed_and_store_pinecone(all_chunks, pinecone_index)
else:
    print("Please set your Pinecone API key")

import google.generativeai as genai
import json

# Configure Gemini API (replace with your API key)
GEMINI_API_KEY = "AIzaSyBH3Bdtuf9LVero5FEuHvzYxtTbS0_ECLM"  # Replace with your actual API key

if GEMINI_API_KEY != "your-gemini-api-key":
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel("gemini-2.0-flash")

def parse_query_with_gemini(query):
    """Parse user query using Gemini API"""
    try:
        prompt = f"""
        Parse the following query and extract relevant information in JSON format:

        Query: "{query}"

        Please return a JSON object with these fields:
        - "entity": The main subject or entity being asked about (e.g., "knee surgery", "dental coverage")
        - "intent": The type of question (e.g., "coverage_check", "benefit_amount", "eligibility")
        - "conditions": Any specific conditions mentioned (true/false)

        Example:
        {{"entity": "knee surgery", "intent": "coverage_check", "conditions": false}}

        Return only the JSON object:
        """

        response = model.generate_content(prompt)

        # Clean and parse response
        response_text = response.text.strip()
        if response_text.startswith('```json'):
            response_text = response_text[7:-3]
        elif response_text.startswith('```'):
            response_text = response_text[3:-3]

        parsed = json.loads(response_text)
        return parsed

    except Exception as e:
        print(f"Error parsing query with Gemini: {e}")
        # Fallback simple parsing
        return {
            'entity': query.lower(),
            'intent': 'coverage_check',
            'conditions': False
        }

# Example usage
if GEMINI_API_KEY != "your-gemini-api-key":
    user_query = "Is knee surgery covered under this policy?"
    parsed = parse_query_with_gemini(user_query)
    print(f"Parsed query: {parsed}")
else:
    print("Please set your Gemini API key")
    # Fallback for testing
    user_query = "Is knee surgery covered under this policy?"
    parsed = {'entity': 'knee surgery', 'intent': 'coverage_check', 'conditions': False}
    print(f"Using fallback parsing: {parsed}")

def retrieve_top_chunks(query, index, top_k=5):
    """Retrieve most relevant chunks from Pinecone"""
    try:
        # Generate query vector
        query_vector = embedding_model.encode(query).tolist()

        # Query Pinecone
        results = index.query(
            vector=query_vector,
            top_k=top_k,
            include_metadata=True
        )

        return results['matches']

    except Exception as e:
        print(f"Error retrieving chunks: {e}")
        return []

# Example retrieval
if 'pinecone_index' in locals() and pinecone_index:
    top_matches = retrieve_top_chunks(user_query, pinecone_index)
    print(f"Found {len(top_matches)} relevant chunks")

    # Display top matches
    for i, match in enumerate(top_matches[:3]):
        print(f"\nMatch {i+1} (Score: {match['score']:.3f}):")
        print(f"File: {match['metadata']['file_name']}")
        print(f"Page: {match['metadata']['page']}")
        print(f"Text: {match['metadata']['text'][:200]}...")
        print("-" * 50)
else:
    print("Pinecone index not available. Using mock data for testing.")
    top_matches = []







from difflib import SequenceMatcher
import re

def normalize_text(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text).lower().strip()

def fuzzy_ratio(a, b):
    return SequenceMatcher(None, a, b).ratio()

def get_ngram_tokens(text, n=2):
    words = text.split()
    return [' '.join(words[i:i+n]) for i in range(len(words)-n+1)]

# Normalize entity
parsed['entity'] = normalize_text(parsed.get('entity', ''))

# Synonym maps
coverage_keywords = ['covered', 'coverage', 'benefit', 'included', 'eligible', 'reimbursed', 'authorized', 'approved']
exclusion_keywords = ['not covered', 'excluded', 'not eligible', 'not included', 'denied', 'not authorized', 'not approved']

# Score tuning logic
for match in top_matches:
    text = normalize_text(match['metadata']['text'])
    original_score = match['score']
    boosted_score = original_score

    # Direct or partial fuzzy match boost
    ratio = fuzzy_ratio(parsed['entity'], text)
    if ratio > 0.6:
        boosted_score += (ratio - 0.6) * 0.5  # scaled fuzzy boost

    # N-gram overlap (e.g., "knee surgery" vs "arthroscopic knee surgery")
    entity_tokens = get_ngram_tokens(parsed['entity'], n=2)
    text_tokens = get_ngram_tokens(text, n=2)
    ngram_overlap = sum(1 for token in entity_tokens if token in text_tokens)
    boosted_score += 0.1 * min(ngram_overlap, 2)

    # Keyword detection
    if any(word in text for word in coverage_keywords):
        boosted_score += 0.05
    if any(word in text for word in exclusion_keywords):
        boosted_score -= 0.05

    # Cap score
    match['score'] = min(boosted_score, 1.0)

from difflib import SequenceMatcher
import re

# Function to normalize entity name
def normalize_text(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text).lower().strip()

# Normalize parsed_query entity
parsed['entity'] = normalize_text(parsed.get('entity', ''))

# Expand synonyms for coverage detection
synonym_map = {
    'covered': ['covered', 'included', 'eligible', 'provided', 'reimbursed', 'approved', 'authorized'],
    'not covered': ['not covered', 'excluded', 'not included', 'denied', 'not eligible', 'not approved', 'not authorized']
}

# Enrich each match with stronger relevance if possible
for match in top_matches:
    text = normalize_text(match['metadata']['text'])
    score = match['score']

    # Boost if partial match with entity
    if SequenceMatcher(None, parsed['entity'], text).ratio() > 0.6:
        match['score'] = min(score + 0.1, 1.0)  # Boost score slightly

    # Keyword presence bonus (weak signal)
    if any(word in text for word in synonym_map['covered']):
        match['score'] += 0.05
    if any(word in text for word in synonym_map['not covered']):
        match['score'] -= 0.05

# Optional: re-normalize scores to [0,1] if any exceed
for match in top_matches:
    match['score'] = min(match['score'], 1.0)







def generate_final_answer(parsed_query, matches, threshold=0.80):
    """Generate final answer based on retrieved chunks"""
    if not matches:
        return {
            'answer': 'No information found',
            'rationale': 'No relevant documents found for your query.',
            'confidence': 0.0
        }

    # Filter matches by similarity score
    relevant_matches = [match for match in matches if match['score'] > threshold]

    if not relevant_matches:
        return {
            'answer': 'Insufficient information',
            'rationale': f'Found {len(matches)} potentially relevant documents, but none meet the confidence threshold.',
            'confidence': max([match['score'] for match in matches])
        }

    # Check for entity mentions in top matches
    entity = parsed_query['entity'].lower()
    entity_found = False
    best_match = None

    for match in relevant_matches:
        text = match['metadata']['text'].lower()
        if entity in text:
            entity_found = True
            best_match = match
            break

    if entity_found and best_match:
        # Look for coverage indicators
        text = best_match['metadata']['text'].lower()
        coverage_indicators = ['covered', 'coverage', 'benefit', 'included', 'eligible']
        exclusion_indicators = ['not covered', 'excluded', 'not eligible', 'not included']

        has_coverage = any(indicator in text for indicator in coverage_indicators)
        has_exclusion = any(indicator in text for indicator in exclusion_indicators)

        if has_exclusion:
            answer = 'No'
            rationale = f"The {entity} appears to be excluded based on information found in {best_match['metadata']['file_name']} on page {best_match['metadata']['page']}."
        elif has_coverage:
            answer = 'Yes'
            rationale = f"The {entity} appears to be covered based on information found in {best_match['metadata']['file_name']} on page {best_match['metadata']['page']}."
        else:
            answer = 'Unclear'
            rationale = f"Information about {entity} was found in {best_match['metadata']['file_name']} on page {best_match['metadata']['page']}, but coverage details are unclear."

        return {
            'answer': answer,
            'rationale': rationale,
            'confidence': best_match['score'],
            'source': {
                'file': best_match['metadata']['file_name'],
                'page': best_match['metadata']['page'],
                'text_excerpt': best_match['metadata']['text'][:300]
            }
        }

    else:
        return {
            'answer': 'No specific information found',
            'rationale': f'No specific information about "{entity}" was found in the documents.',
            'confidence': relevant_matches[0]['score'] if relevant_matches else 0.0
        }

# Generate final answer
final_result = generate_final_answer(parsed, top_matches)
print("\n" + "="*60)
print("FINAL ANSWER")
print("="*60)
print(f"Query: {user_query}")
print(f"Answer: {final_result['answer']}")
print(f"Rationale: {final_result['rationale']}")
print(f"Confidence: {final_result.get('confidence', 0):.3f}")

if 'source' in final_result:
    print(f"\nSource Information:")
    print(f"File: {final_result['source']['file']}")
    print(f"Page: {final_result['source']['page']}")
    print(f"Excerpt: {final_result['source']['text_excerpt']}...")

# Path to your uploaded test PDF (uploaded directly on Jupyter)
test_pdf_path = 'testingpolicy.pdf'  # ensure correct filename if extension differs

# Load and chunk the test PDF
test_chunks = load_and_chunk_pdf(test_pdf_path)
print(f"Loaded '{test_pdf_path}': {len(test_chunks)} chunks")

# Show sample content
if test_chunks:
    print("\nSample chunk content:")
    print(f"Text: {test_chunks[0]['text'][:200]}...")
    print(f"Metadata: {test_chunks[0]['metadata']}")
else:
    print("No chunks extracted from the test PDF.")

import numpy as np

def answer_question_from_chunks(question, chunks, top_k=3):
    """Get top K relevant chunks using cosine similarity"""
    query_embedding = embedding_model.encode(question)
    chunk_similarities = []

    for chunk in chunks:
        chunk_embedding = embedding_model.encode(chunk['text'])
        similarity = float(np.dot(query_embedding, chunk_embedding) /
                           (np.linalg.norm(query_embedding) * np.linalg.norm(chunk_embedding)))

        chunk_similarities.append({
            'chunk': chunk,
            'similarity': similarity
        })

    # Sort by similarity and return top K
    chunk_similarities.sort(key=lambda x: x['similarity'], reverse=True)
    return chunk_similarities[:top_k]

# List of questions
questions = [
    "What is the grace period for premium payment under the National Parivar Mediclaim Plus Policy?",
    "What is the waiting period for pre-existing diseases (PED) to be covered?",
    "Does this policy cover maternity expenses, and what are the conditions?",
    "What is the waiting period for cataract surgery?",
    "Are the medical expenses for an organ donor covered under this policy?",
    "What is the No Claim Discount (NCD) offered in this policy?",
    "Is there a benefit for preventive health check-ups?",
    "How does the policy define a 'Hospital'?",
    "What is the extent of coverage for AYUSH treatments?",
    "Are there any sub-limits on room rent and ICU charges for Plan A?"
]

# Loop through and test
for idx, q in enumerate(questions):
    print(f"\n\n{'='*80}")
    print(f"Q{idx+1}: {q}")
    print(f"{'='*80}")

    top_results = answer_question_from_chunks(q, test_chunks)

    for i, result in enumerate(top_results):
        print(f"\nTop {i+1} Result (Score: {result['similarity']:.3f})")
        print(f"From page: {result['chunk']['metadata']['page']} - {result['chunk']['metadata']['file_name']}")
        print(f"Text: {result['chunk']['text'][:500]}...\n")

